### ISSUE TITLE
MetaBase arm arch setup failed

### ISSUE THREAD

**Issue by GavinChowUp** [trevorr/metabase-arm64#2]
Hi @trevorr:
     Thanks for giving the nice image, I'm new to Metabase and want to run it on M1, I followed your Dockerfile and use buildx to build the image to local but when I run it, it failed for this cause: It seems missed some files. How can I fix it? (since I want to check if it works, so I build the image on my x86 and run it on x86 first, this is caused on x86.)

```log
2022-08-25 00:05:40,597 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
2022-08-25 00:05:40,655 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2022-08-25 00:05:40,658 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2022-08-25 00:05:40,659 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2022-08-25 00:05:40,663 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2022-08-25 00:05:40,704 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2022-08-25 00:05:40,708 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2022-08-25 00:05:40,737 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
2022-08-25 00:05:40,742 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc]) 🚚
2022-08-25 00:05:40,757 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2022-08-25 00:05:40,761 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2022-08-25 00:05:40,880 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2022-08-25 00:05:40,884 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2022-08-25 00:05:40,897 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-common...
2022-08-25 00:05:40,901 INFO driver.impl :: Registered abstract driver :presto-common  🚚
2022-08-25 00:05:40,904 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true
2022-08-25 00:05:40,907 INFO plugins.dependencies :: Metabase Presto JDBC Driver dependency {:plugin Presto Common Driver} satisfied? true
2022-08-25 00:05:40,908 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase Presto JDBC Driver" "Metabase Presto Driver"]
2022-08-25 00:05:40,912 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
2022-08-25 00:05:40,916 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:presto-common]) 🚚
2022-08-25 00:05:40,918 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
2022-08-25 00:05:40,923 INFO driver.impl :: Registered driver :presto (parents: [:presto-common]) 🚚
2022-08-25 00:05:41,022 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
2022-08-25 00:05:41,026 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
2022-08-25 00:05:41,054 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2022-08-25 00:05:41,057 INFO driver.impl :: Registered driver :druid  🚚
2022-08-25 00:05:41,063 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2022-08-25 00:05:41,077 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
2022-08-25 00:05:41,101 INFO db.setup :: Verifying h2 Database Connection ...
org.h2.message.DbException: Log file error: "/app/metabase.db.trace.db", cause: "java.io.FileNotFoundException: /app/metabase.db.trace.db (Permission denied)" [90034-197]
org.h2.message.DbException: Log file error: "/app/metabase.db.trace.db", cause: "java.io.FileNotFoundException: /app/metabase.db.trace.db (Permission denied)" [90034-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
	at org.h2.message.TraceSystem.write(TraceSystem.java:242)
	at org.h2.message.Trace.error(Trace.java:182)
	at org.h2.engine.Database.setBackgroundException(Database.java:2110)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2506)
	at org.h2.mvstore.MVStore.panic(MVStore.java:383)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:364)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:245)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:242)
	at metabase.db.setup$fn__33589$verify_db_connection__33594$fn__33595$fn__33596.invoke(setup.clj:100)
	at metabase.db.setup$fn__33589$verify_db_connection__33594$fn__33595.invoke(setup.clj:100)
	at metabase.db.setup$fn__33589$verify_db_connection__33594.invoke(setup.clj:94)
	at metabase.db.setup$setup_db_BANG_$fn__33624$fn__33625.invoke(setup.clj:142)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:694)
	at metabase.util$do_with_us_locale.invoke(util.clj:680)
	at metabase.db.setup$setup_db_BANG_$fn__33624.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__33732.invoke(db.clj:61)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG_.invokeStatic(core.clj:91)
	at metabase.core$init_BANG_.invoke(core.clj:74)
	at metabase.core$start_normally.invokeStatic(core.clj:135)
	at metabase.core$start_normally.invoke(core.clj:129)
	at metabase.core$_main.invokeStatic(core.clj:168)
	at metabase.core$_main.doInvoke(core.clj:162)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Log file error: "/app/metabase.db.trace.db", cause: "java.io.FileNotFoundException: /app/metabase.db.trace.db (Permission denied)" [90034-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 63 more
Caused by: java.io.FileNotFoundException: /app/metabase.db.trace.db (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at org.h2.store.fs.FilePathDisk.newOutputStream(FilePathDisk.java:287)
	at org.h2.store.fs.FileUtils.newOutputStream(FileUtils.java:236)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:306)
	... 60 more
2022-08-25 00:05:42,959 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase h2 DB. {}
	at metabase.db.setup$fn__33589$verify_db_connection__33594$fn__33595$fn__33596.invoke(setup.clj:102)
	at metabase.db.setup$fn__33589$verify_db_connection__33594$fn__33595.invoke(setup.clj:100)
	at metabase.db.setup$fn__33589$verify_db_connection__33594.invoke(setup.clj:94)
	at metabase.db.setup$setup_db_BANG_$fn__33624$fn__33625.invoke(setup.clj:142)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:694)
	at metabase.util$do_with_us_locale.invoke(util.clj:680)
	at metabase.db.setup$setup_db_BANG_$fn__33624.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__33732.invoke(db.clj:61)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG_.invokeStatic(core.clj:91)
	at metabase.core$init_BANG_.invoke(core.clj:74)
	at metabase.core$start_normally.invokeStatic(core.clj:135)
	at metabase.core$start_normally.invoke(core.clj:129)
	at metabase.core$_main.invokeStatic(core.clj:168)
	at metabase.core$_main.doInvoke(core.clj:162)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: null [90028-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:192)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:245)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:242)
	at metabase.db.setup$fn__33589$verify_db_connection__33594$fn__33595$fn__33596.invoke(setup.clj:100)
	... 21 more
Caused by: java.lang.IllegalStateException: Could not open file nio:/app/metabase.db.mv.db [1.4.197/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:179)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	... 50 more
Caused by: java.io.FileNotFoundException: /app/metabase.db.mv.db (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
	at org.h2.store.fs.FileNio.<init>(FilePathNio.java:43)
	at org.h2.store.fs.FilePathNio.open(FilePathNio.java:23)
	at org.h2.mvstore.FileStore.open(FileStore.java:155)
	... 53 more
```
     
My steps is : 

```sh
docker buildx build  --load --platform linux/amd64 --tag gavinup/metabase:1.41.4 --build-arg metabase_repo=metabase-enterprise --build-arg metabase_version=v1.41.4 .
```

DockerFile is :

```docker
ARG metabase_repo=metabase
ARG metabase_version=v1.41.4
FROM metabase/${metabase_repo}:${metabase_version} as metabase

# From https://github.com/metabase/metabase/issues/13119#issuecomment-1000350647

FROM ubuntu:22.04

ENV FC_LANG en-US LC_CTYPE en_US.UTF-8

# dependencies
RUN apt-get update -yq && apt-get install -yq bash fonts-dejavu-core fonts-dejavu-extra fontconfig curl openjdk-11-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    mkdir -p /app/certs && \
    curl https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem -o /app/certs/rds-combined-ca-bundle.pem  && \
    keytool -noprompt -import -trustcacerts -alias aws-rds -file /app/certs/rds-combined-ca-bundle.pem -keystore /etc/ssl/certs/java/cacerts -keypass changeit -storepass changeit && \
    curl https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem -o /app/certs/DigiCertGlobalRootG2.crt.pem  && \
    keytool -noprompt -import -trustcacerts -alias azure-cert -file /app/certs/DigiCertGlobalRootG2.crt.pem -keystore /etc/ssl/certs/java/cacerts -keypass changeit -storepass changeit && \
    mkdir -p /plugins && chmod a+rwx /plugins && \
    useradd --shell /bin/bash metabase


WORKDIR /app
USER metabase

# copy app from the offical image
COPY --from=metabase --chown=metabase /app /app

# expose our default runtime port
EXPOSE 3000

# run it
ENTRYPOINT ["/app/run_metabase.sh"]
```

Run command  :

```sh
docker run -it -p 3000:3000 --name metabase1 gavinup/metabase:1.41.4
```

**Comment by GavinChowUp** [comment]
since I want to check if it works, so I build the first image on my x86 and run it on x86.

**Comment by trevorr** [comment]
This looks like a setup error. It only uses h2 if you don't set up another database. I know docker, not metabase, so I'm really not in a position to help. 😄 You might try using docker-compose to run and configure a database: https://github.com/trevorr/metabase-arm64/issues/1#issuecomment-1202990058
